# Generated by Django 5.0.2 on 2024-02-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('seria', models.CharField(max_length=8)),
                ('pass_num', models.CharField(max_length=20)),
                ('kem', models.CharField(max_length=255)),
                ('date_vidachi', models.DateField()),
                ('idnum', models.CharField(max_length=255)),
                ('birthplace', models.CharField(max_length=255)),
                ('city_of_residence', models.CharField(max_length=255)),
                ('adress_residence', models.CharField(max_length=255)),
                ('HomeNum', models.CharField(max_length=7)),
                ('mobnum', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('city_of_living', models.CharField(max_length=255)),
                ('adress_living', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('citizen', models.CharField(max_length=255)),
                ('handicap', models.CharField(max_length=255)),
                ('senior', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('cod', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('debet', models.FloatField()),
                ('credit', models.FloatField()),
                ('saldo', models.FloatField()),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('open_time', models.DateField()),
                ('close_time', models.DateField()),
                ('number', models.BigIntegerField()),
                ('valute', models.CharField(max_length=255)),
                ('srok', models.CharField(max_length=255)),
                ('sum', models.FloatField()),
                ('percent', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('schetActive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schetA', to='main.schet')),
                ('schetPassive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schetB', to='main.schet')),
            ],
        ),
    ]
