# Generated by Django 5.0.2 on 2024-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
