# Generated by Django 5.0.2 on 2024-02-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_deposit_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='schet',
            name='ostatok',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
