# Generated by Django 5.0.2 on 2024-02-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_schet_ostatok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('open_time', models.DateField()),
                ('close_time', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
                ('number', models.BigIntegerField()),
                ('valute', models.CharField(max_length=255)),
                ('srok', models.CharField(max_length=255)),
                ('sum', models.FloatField()),
                ('percent', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('schetActive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schetCA', to='main.schet')),
                ('schetPassive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schetCB', to='main.schet')),
            ],
        ),
    ]
